# Generated by Django 4.2.4 on 2023-08-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
